#!/usr/bin/env bash
#
# ############################################################################
# Project: torctl (none)
# File...: torctl
# Created: Monday, 2022/11/21 - 20:55:29
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Saturday, 2023/01/14 - 20:47:16
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.0.4.114
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#

# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~    
source ./xSHELL/initialize
 
use args torctl.lib 

# check requirements for this app
xrequirements docker curl jq grep iptables

# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~    
xarg --id -s,--start   --var action:start   --desc "start Tor Server and redirect traffic throug it"    
xarg --id -t,--stop    --var action:stop    --desc "stop Tor Server and restore firewall rules"    
xarg --id -S,--status  --var action:status  --desc "show current status"    
xarg --id -r,--restart --var action:restart --desc "restart Tor Server"    

# run params
xrun --xreject-unknow --xrequire-one --xversionrc "$@"    

# check selected action
case "$action" in
    start   ) actionStart   ;;
    stop    ) actionStop    ;;
    status  ) actionStatus  ;;
    restart ) actionRestart ;;
esac