#!/usr/bin/env bash
#
# ############################################################################
# Project: torctl (none)
# File...: torctl
# Created: Monday, 2022/11/21 - 20:55:29
# Author.: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Last Modified: Saturday, 2025/08/02 - 09:48:10
# Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Version: 0.1.0.146
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
# Description: 
#  >
# ############################################################################
# HISTORY:
#

# shellcheck disable=1090,2154
# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~    
source "$xSHELL_INIT"
use args colors utils torctl.lib 
xrequirements docker curl jq grep "iptables|pfctl"

# ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~    
xarg --id -s,--start   --desc "start Tor Server and redirect traffic throug it"
xarg --id -t,--stop    --desc "stop Tor Server and restore firewall rules"
xarg --id -S,--status  --desc "show current status"
xarg --id -r,--restart --desc "restart Tor Server"

xarg --header "Simple script to setup a tor-server via docker and route all traffic of your system to it."
xarg --footer "${YELLOW}Warning! You must be root to change firewall rules and start the tor server.${RESET}"

# run arguments
xrun --xreject-unknow --xrequire-one --xversionrc --xcolors "$@"    

# check selected argument
case "$xarg" in
    s) actionStart   ;;
    t) actionStop    ;;
    S) actionStatus  ;;
    r) actionRestart ;;
esac